gui:
  theme:
    activeBorderColor:
      - '#e78a4e'
      - bold
    searchingActiveBorderColor:
      - '#d8a657'
      - bold
    inactiveBorderColor:
      - '#665c54'
    optionsTextColor:
      - '#7daea3'
    selectedLineBgColor:
      - '#3c3836'
    inactiveViewSelectedLineBgColor:
      - '#32302f'
    cherryPickedCommitBgColor:
      - '#3c3836'
    cherryPickedCommitFgColor:
      - '#a9b665'
    markedBaseCommitBgColor:
      - '#3c3836'
    markedBaseCommitFgColor:
      - '#d8a657'
    unstagedChangesColor:
      - '#ea6962'
    defaultFgColor:
      - '#d4be98'
  authorColors:
    '*': '#89b482'
