# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x0d2030ff
rootcolor = 0x0d2030ff
bordercolor = 0x5d6b71ff
focuscolor = 0x67bfe4ff
maximizescreencolor = 0x5c74d6ff
urgentcolor = 0xfd4663ff
scratchpadcolor = 0x825ed4ff
globalcolor = 0x0c678dff
overlaycolor = 0x10236fff
