# Tokyo Night Moon theme colors
thm_bg="#222436"
thm_fg="#c8d3f5"
thm_cyan="#86e1fc"
thm_black="#1b1d2b"
thm_gray="#3a3f5a"
thm_magenta="#c099ff"
thm_pink="#ff757f"
thm_red="#ff757f"
thm_green="#c3e88d"
thm_yellow="#ffc777"
thm_blue="#82aaff"
thm_orange="#ff9e64"
thm_black4="#444a73"

# Status bar settings
set -g status "on"
set -g status-bg "${thm_bg}"
set -g status-justify "left"
set -g status-left-length "100"
set -g status-right-length "100"

# Messages
set -g message-style "fg=${thm_cyan},bg=${thm_gray},align=centre"
set -g message-command-style "fg=${thm_cyan},bg=${thm_gray},align=centre"

# Panes
set -g pane-border-style "fg=${thm_gray}"
set -g pane-active-border-style "fg=${thm_blue}"

# Windows
set -g window-status-activity-style "fg=${thm_fg},bg=${thm_bg},none"
set -g window-status-separator ""
set -g window-status-style "fg=${thm_fg},bg=${thm_bg},none"

# Statusline - current window
set -g window-status-current-format "#[bg=${thm_bg},fg=${thm_gray},nobold,nounderscore,noitalics]#[fg=${thm_fg},bg=${thm_gray},bold,italics]#W #[fg=${thm_bg},bg=${thm_blue},bold] #I#[bg=${thm_bg},fg=${thm_blue}]" 

# Statusline - other windows
set -g window-status-format "#[bg=${thm_bg},fg=${thm_gray},nobold,nounderscore,noitalics]#[fg=${thm_fg},bg=${thm_gray}]#W #[fg=${thm_bg},bg=${thm_orange}] #I#[bg=${thm_bg},fg=${thm_orange}]"

# Statusline - left side
set -g @local "#{?client_prefix,#[bg=${thm_magenta}],#[bg=${thm_cyan}]}#[fg=${thm_gray}]#{?client_prefix,#[fg=${thm_magenta}],#[fg=${thm_cyan}]}#[bg=${thm_bg}]#{?client_prefix,#[fg=${thm_magenta}],#[fg=${thm_cyan}]}#[bg=${thm_gray}]#{?client_prefix,#[bg=${thm_magenta}],#[bg=${thm_cyan}]}#[fg=${thm_bg}]󱧑 #[fg=${thm_fg},bg=${thm_gray}] #S#[bg=${thm_bg},fg=${thm_gray}]#[bg=${thm_bg},fg=${thm_green},nobold,nounderscore,noitalics]#[fg=${thm_bg},bg=${thm_green},nobold,nounderscore,noitalics]󰇅 #[fg=${thm_fg},bg=${thm_gray}] #h#[bg=${thm_bg},fg=${thm_gray}] "
set -g @remote "#{?client_prefix,#[bg=${thm_magenta}],#[bg=${thm_red}]}#[fg=${thm_gray}]#{?client_prefix,#[fg=${thm_magenta}],#[fg=${thm_red}]}#[bg=${thm_bg}]#{?client_prefix,#[fg=${thm_magenta}],#[fg=${thm_red}]}#[bg=${thm_gray}]#{?client_prefix,#[bg=${thm_magenta}],#[bg=${thm_red}]}#[fg=${thm_bg}]󰢹 #[fg=${thm_fg},bg=${thm_gray}] REMOTE#[bg=${thm_bg},fg=${thm_gray}]#[bg=${thm_bg},fg=${thm_green},nobold,nounderscore,noitalics]#[fg=${thm_bg},bg=${thm_green},nobold,nounderscore,noitalics]󰇅 #[fg=${thm_fg},bg=${thm_gray}] #h#[bg=${thm_bg},fg=${thm_gray}] "
set -g status-left "#{E:@local}"

# Statusline - right side
set -g @clock "#[bg=${thm_bg},fg=${thm_magenta},nobold,nounderscore,noitalics]#[fg=${thm_bg},bg=${thm_magenta},nobold,nounderscore,noitalics] #[fg=${thm_fg},bg=${thm_gray}] %I:%M %p#[bg=${thm_bg},fg=${thm_gray}] "
set -g status-right '#{E:@clock}'

bind-key -n MouseDown1StatusLeft run-shell "sesh connect \"$(
  sesh list --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  C-a all C-t tmux C-g configs C-x zoxide C-d tmux kill C-f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}'
)\""
bind-key -n MouseDown3StatusLeft run-shell "sesh window \"$(sesh window | fzf-tmux -p 60%,50% --prompt '🪟  ')\""

# Modes
set -g clock-mode-colour "${thm_blue}"
set -g mode-style "fg=${thm_blue} bg=${thm_black4} bold"
set -g status-position top

