color0 #0d2030
color1 #fd4663
color2 #67bfe4
color3 #5c74d6
color4 #825ed4
color5 #93d1ec
color6 #96a6e9
color7 #f2f3f3
color8 #5d6b71
color9 #fd4663
color10 #67bfe4
color11 #5c74d6
color12 #825ed4
color13 #93d1ec
color14 #96a6e9
color15 #f2f3f3

cursor                #f2f3f3
cursor_text_color     #0d2030
background            #0d2030
foreground            #f2f3f3
selection_foreground  #afb4b6
selection_background  #112a40
active_border_color   #67bfe4
inactive_border_color #112a40
url_color             #67bfe4

active_tab_foreground   #182125
active_tab_background   #67bfe4
inactive_tab_foreground #afb4b6
inactive_tab_background #112a40
cursor_trail_color      #afb4b6
