color0 #082c49
color1 #fd4663
color2 #72cdf0
color3 #728ef0
color4 #9572f0
color5 #8cd6f3
color6 #8ca3f3
color7 #f2f3f3
color8 #5d6c71
color9 #fd4663
color10 #72cdf0
color11 #728ef0
color12 #9572f0
color13 #8cd6f3
color14 #8ca3f3
color15 #f2f3f3

cursor                #f2f3f3
cursor_text_color     #062137
background            #062137
foreground            #f2f3f3
selection_foreground  #afb4b6
selection_background  #082c49
active_border_color   #72cdf0
inactive_border_color #082c49
url_color             #72cdf0

active_tab_foreground   #182125
active_tab_background   #72cdf0
inactive_tab_foreground #afb4b6
inactive_tab_background #082c49
cursor_trail_color      #afb4b6
