[bar.default]
border = "surface"
capsule = true
capsule_border = "secondary"
capsule_padding = 8.0
capsule_thickness = 0.85999999999999999
center = [ "audio_visualizer", "clock" ]
color = "primary"
end = [ "group:g4", "group:g2", "group:g3" ]
margin_edge = 4.0
margin_ends = 4.0
padding = 6
shadow = false
start = [ "group:g1" ]

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    border = "secondary"
    enabled = true
    fill = "surface"
    id = "g1"
    members = [ "launcher", "active-workspace", "workspaces", "active_window" ]
    opacity = 1.0
    padding = 8.0

    [[bar.default.capsule_group]]
    accordion = true
    accordion_direction = "end"
    border = "secondary"
    enabled = true
    fill = "surface_variant"
    id = "g2"
    members = [ "tray", "notifications", "clipboard" ]
    opacity = 1.0
    padding = 8.0

    [[bar.default.capsule_group]]
    accordion = true
    accordion_direction = "start"
    border = "secondary"
    enabled = true
    fill = "surface"
    foreground = "primary"
    id = "g3"
    members = [ "session", "network", "bluetooth", "widget", "battery" ]
    opacity = 1.0
    padding = 8.0

    [[bar.default.capsule_group]]
    accordion = true
    accordion_direction = "start"
    border = "secondary"
    enabled = true
    fill = "surface_variant"
    id = "g4"
    members = [ "widget_2", "summary" ]
    opacity = 1.0
    padding = 8.0

[desktop_widgets]
schema_version = 1
widget_order = [
    "desktop-widget-0000000000000001",
    "desktop-widget-0000000000000002",
    "desktop-widget-0000000000000004",
    "desktop-widget-0000000000000005",
    "desktop-widget-0000000000000006"
]

    [desktop_widgets.grid]
    cell_size = 32
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 163.98719787597656
    box_width = 257.11016845703125
    cx = 1774.66455078125
    cy = 479.8135986328125
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        display = "graph"
        gauge_layout = "horizontal"
        stat = "cpu_usage"
        stat2 = "cpu_temp"

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 163.63998413085938
    box_width = 256.39999389648438
    cx = 1775.0196533203125
    cy = 316.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        color = "secondary"
        display = "graph"
        gauge_layout = "horizontal"
        stat = "ram_pct"
        stat2 = "swap_pct"

    [desktop_widgets.widget.desktop-widget-0000000000000004]
    box_height = 164.16000366210938
    box_width = 356.39999389648438
    cx = 191.81394958496094
    cy = 142.08000183105469
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "weather"

        [desktop_widgets.widget.desktop-widget-0000000000000004.settings]
        show_forecast = false

    [desktop_widgets.widget.desktop-widget-0000000000000005]
    box_height = 256.0
    box_width = 352.0
    cx = 189.61395263671875
    cy = 362.00640869140625
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "media_player"

        [desktop_widgets.widget.desktop-widget-0000000000000005.settings]
        layout = "vertical"

    [desktop_widgets.widget.desktop-widget-0000000000000006]
    box_height = 163.5078125
    box_width = 256.129638671875
    cx = 1775.15478515625
    cy = 152.25250244140625
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000006.settings]
        display = "graph"
        network_speed_compact = false
        stat = "net_rx"
        stat2 = "net_tx"

[dock]
active_monitor_only = true
auto_hide = true
enabled = true
pinned = []
reserve_space = false
show_dots = true

[idle]
behavior_order = [ "lock", "screen-off", "suspend" ]
pre_action_fade_seconds = 0.0

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660

    [idle.behavior.suspend]
    action = "suspend"
    enabled = true
    lock_before_suspend = true
    timeout = 900

[location]
auto_locate = true

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1", "lockscreen-widget-0000000000000001", "lockscreen-widget-0000000000000002" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 957.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        center_password_text = false
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 160.0
    box_width = 448.0
    cx = 240.0
    cy = 92.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        clock_style = "digital"
        color = "on_surface"
        font_family = "JetBrainsMono Nerd Font"
        format = "{:%-I:%M %p}"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 192.0
    box_width = 432.0
    cx = 240.0
    cy = 284.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "weather"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background = false
        shadow = true

[osd]
position = "top_right"

[plugin_settings."gustav0ar/drive-health"]
drives_placement = "attached"

[plugin_settings."kenn/keybind-cheatsheet"]
cheatsheet_placement = "attached"

[plugin_settings."piero-93/battery-power-management"]
panel_placement = "floating"

[plugin_settings."weinguyen/procmon"]
panel_placement = "attached"

[plugins]
enabled = [
    "salemsayed/niri-active-workspace",
    "kenn/keybind-cheatsheet",
    "weinguyen/procmon",
    "blackbartblues/audio-switcher",
    "gustav0ar/drive-health"
]

[shell]
avatar_path = "/home/fadewind/.config/assets/profile-pic/zel_icon.jpg"
external_ip_enabled = true
font_family = "JetBrainsMono NF"
launch_apps_as_systemd_services = true
niri_overview_type_to_launch_enabled = true
panel_anchor_bar = "default"
polkit_agent = true
settings_show_advanced = true
setup_wizard_enabled = false
telemetry_enabled = false
time_format = "{:%-I:%M %p}"

    [shell.panel]
    clipboard_placement = "attached"
    floating_layer = "top"
    launcher_placement = "attached"
    open_near_click_clipboard = true
    open_near_click_launcher = true
    open_near_click_wallpaper = true

    [shell.screenshot]
    freeze_screen = true

[theme]
builtin = "Gruvbox"
community_palette = "Gruvbox Material"
source = "community"
wallpaper_scheme = "vibrant"

    [theme.templates]
    builtin_ids = [ "btop", "kitty", "niri", "qt" ]
    community_ids = [ "discord" ]

[wallpaper]
directory = "/home/fadewind/.config/assets/wallpapers"
fill_mode = "center"

    [wallpaper.default]
    path = "/home/fadewind/.config/assets/wallpapers/XIV_Fire.jpg"

    [wallpaper.last]
    path = "/home/fadewind/.config/assets/wallpapers/XIV_Fire.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/fadewind/.config/assets/wallpapers/XIV_Fire.jpg"

[weather]
unit = "imperial"

[widget.active-workspace]
glyph = "layout-distribute-horizontal-filled"
type = "salemsayed/niri-active-workspace:active-workspace"

[widget.active_window]
min_length = 0
title_scroll = "on_hover"

[widget.clock]
anchor = true
format = "{:%-I:%M %p}"
timezone = "America/New_York"

[widget.launcher]
custom_image = "/run/current-system/sw/share/icons/hicolor/scalable/apps/nix-snowflake.svg"

[widget.media]
hide_when_no_media = true

[widget.network]
show_label = false

[widget.summary]
type = "gustav0ar/drive-health:summary"

[widget.widget]
type = "blackbartblues/audio-switcher:widget"

[widget.widget_2]
capsule_foreground = "primary"
color = "primary"
enable_scroll = false
icon_color = "primary"
show_count = false
type = "weinguyen/procmon:widget"

[widget.workspaces]
empty_color = "tertiary"
enabled = false
